import { ChamadoService } from './chamadoService';
import { ManutencaoService } from './manutencaoService';
import { EquipamentoService } from './equipamentoService';
import { UsuarioService } from './usuarioService';
import { FuncionarioService } from './funcionarioService';
import { FiltrosRelatorio, ResultadoRelatorio } from '../types/relatorio';
import { getIntervalo, isInInterval, durationHours, formatDuration } from '../utils/dateGrouping';
import { formatCurrency } from '../utils/formatters';

export interface OrdemRelatorio { id:string; abertura:string; cliente:string; equipamento:string; tecnico:string; prioridade:string; status:string; conclusao:string|null; duracao:number|null; descricao:string; }
export interface ReparoRelatorio { id:string; data:string; equipamento:string; codigo:string; cliente:string; descricao:string; tecnico:string; status:string; custo:number; conclusao:string|null; }
export interface EquipeRelatorio { id:string; nome:string; cargo:string; especialidades:string; status:string; atribuidas:number; concluidas:number; andamento:number; taxa:number; reparos:number; duracao:number|null; valor:number; }
export interface ClienteEquipamentoRelatorio { tipo:'CLIENTE'|'EQUIPAMENTO'; id:string; nome:string; contato:string; codigo:string; fabricante:string; modelo:string; cliente:string; equipamentos:number; ordens:number; concluidas:number; reparos:number; ultima:string|null; status:string; }

const includes = (value:string, query:string):boolean => value.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
const finite = (value:string):number|null => value.trim() !== '' && Number.isFinite(Number(value)) ? Number(value) : null;

export class RelatorioService {
  public static ordens(f:FiltrosRelatorio):ResultadoRelatorio<OrdemRelatorio> {
    const intervalo=getIntervalo(f.periodo,f.dataInicial,f.dataFinal), users=new Map(UsuarioService.getAll().map(x=>[x.id,x])), eqs=new Map(EquipamentoService.getAll().map(x=>[x.id,x]));
    const linhas=ChamadoService.getAll().filter(x=>isInInterval(x.criadoEm,intervalo) && (!f.status||x.status===f.status) && (!f.prioridade||x.prioridade===f.prioridade) && (!f.clienteId||x.clienteId===f.clienteId) && (!f.equipamentoId||x.equipamentoId===f.equipamentoId) && (!f.tecnicoId||x.tecnicoResponsavelId===f.tecnicoId) && (!f.pesquisa||includes(`${x.id} ${x.titulo} ${x.descricao}`,f.pesquisa))).map(x=>({id:x.id,abertura:x.criadoEm,cliente:users.get(x.clienteId)?.nome??'Cliente removido',equipamento:eqs.get(x.equipamentoId)?`${eqs.get(x.equipamentoId)!.codigo} — ${eqs.get(x.equipamentoId)!.fabricante} ${eqs.get(x.equipamentoId)!.modelo}`:'Equipamento removido',tecnico:FuncionarioService.resolveName(x.tecnicoResponsavelId,x.tecnicoResponsavelNomeLegado),prioridade:x.prioridade,status:x.status,conclusao:x.concluidoEm,duracao:durationHours(x.criadoEm,x.concluidoEm),descricao:x.descricao}));
    const done=linhas.filter(x=>x.status==='CONCLUIDO'), durations=done.map(x=>x.duracao).filter((x):x is number=>x!==null);
    return {intervalo,linhas,resumo:[['Total de ordens',linhas.length],['Abertas',linhas.filter(x=>x.status==='ABERTO').length],['Em andamento',linhas.filter(x=>x.status==='EM_ATENDIMENTO').length],['Concluídas',done.length],['Canceladas',linhas.filter(x=>x.status==='CANCELADO').length],['Urgentes',linhas.filter(x=>x.prioridade==='URGENTE').length],['Taxa de conclusão',linhas.length?`${(done.length/linhas.length*100).toFixed(1)}%`:'0%'],['Tempo médio',formatDuration(durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:null)]].map(([rotulo,valor])=>({rotulo:String(rotulo),valor:String(valor)}))};
  }

  public static reparos(f:FiltrosRelatorio):ResultadoRelatorio<ReparoRelatorio> {
    const intervalo=getIntervalo(f.periodo,f.dataInicial,f.dataFinal), eqs=new Map(EquipamentoService.getAll().map(x=>[x.id,x])), users=new Map(UsuarioService.getAll().map(x=>[x.id,x])), min=finite(f.valorMinimo), max=finite(f.valorMaximo);
    const linhas=ManutencaoService.getAll().filter(x=>isInInterval(x.dataInicio,intervalo)&&(!f.status||x.status===f.status)&&(!f.equipamentoId||x.equipamentoId===f.equipamentoId)&&(!f.tecnicoId||x.tecnicoResponsavelId===f.tecnicoId)&&(!f.clienteId||eqs.get(x.equipamentoId)?.clienteId===f.clienteId)&&(min===null||x.custo>=min)&&(max===null||x.custo<=max)&&(!f.pesquisa||includes(x.descricao,f.pesquisa))).map(x=>{const eq=eqs.get(x.equipamentoId);return{id:x.id,data:x.dataInicio,equipamento:eq?`${eq.tipo} — ${eq.fabricante} ${eq.modelo}`:'Equipamento removido',codigo:eq?.codigo??'-',cliente:eq?users.get(eq.clienteId)?.nome??'Cliente removido':'-',descricao:x.descricao,tecnico:FuncionarioService.resolveName(x.tecnicoResponsavelId,x.tecnicoResponsavelNomeLegado),status:x.status,custo:Number.isFinite(x.custo)?x.custo:0,conclusao:x.dataConclusao};});
    // Totais financeiros consideram somente serviços concluídos e não cancelados.
    const values=linhas.filter(x=>x.status==='CONCLUIDA'&&x.custo>=0).map(x=>x.custo), total=values.reduce((a,b)=>a+b,0);
    return{intervalo,linhas,resumo:[['Total de reparos',linhas.length],['Em andamento',linhas.filter(x=>x.status==='EM_ANDAMENTO').length],['Concluídos',values.length],['Cancelados',linhas.filter(x=>x.status==='CANCELADA').length],['Valor total',formatCurrency(total)],['Valor médio',formatCurrency(values.length?total/values.length:0)],['Maior valor',formatCurrency(values.length?Math.max(...values):0)],['Menor valor',formatCurrency(values.length?Math.min(...values):0)]].map(([rotulo,valor])=>({rotulo:String(rotulo),valor:String(valor)}))};
  }

  public static equipe(f:FiltrosRelatorio):ResultadoRelatorio<EquipeRelatorio> {
    const intervalo=getIntervalo(f.periodo,f.dataInicial,f.dataFinal), orders=ChamadoService.getAll().filter(x=>isInInterval(x.criadoEm,intervalo)), repairs=ManutencaoService.getAll().filter(x=>isInInterval(x.dataInicio,intervalo));
    const staff=FuncionarioService.getAll().filter(x=>(!f.tecnicoId||x.id===f.tecnicoId)&&(!f.cargo||x.cargo===f.cargo)&&(!f.status||x.status===f.status)&&(!f.especialidade||x.especialidades.includes(f.especialidade as never)));
    const ids=new Set([...staff.map(x=>x.id),...orders.map(x=>x.tecnicoResponsavelId).filter(Boolean) as string[],...repairs.map(x=>x.tecnicoResponsavelId).filter(Boolean) as string[]]);
    const linhas=[...ids].map(id=>{const person=FuncionarioService.getById(id), assigned=orders.filter(x=>x.tecnicoResponsavelId===id), done=assigned.filter(x=>x.status==='CONCLUIDO'), ongoing=assigned.filter(x=>['ABERTO','EM_ATENDIMENTO','AGUARDANDO_USUARIO'].includes(x.status)), completedRepairs=repairs.filter(x=>x.tecnicoResponsavelId===id&&x.status==='CONCLUIDA'), ds=done.map(x=>durationHours(x.criadoEm,x.concluidoEm)).filter((x):x is number=>x!==null);return{id,nome:person?.nome??'Funcionário removido',cargo:person?.cargo??'-',especialidades:person?.especialidades.join(', ')??'-',status:person?.status??'INATIVO',atribuidas:assigned.length,concluidas:done.length,andamento:ongoing.length,taxa:assigned.length?done.length/assigned.length*100:0,reparos:completedRepairs.length,duracao:ds.length?ds.reduce((a,b)=>a+b,0)/ds.length:null,valor:completedRepairs.reduce((sum,x)=>sum+(Number.isFinite(x.custo)?x.custo:0),0)};}).filter(x=>!f.pesquisa||includes(x.nome,f.pesquisa));
    const allDurations=linhas.map(x=>x.duracao).filter((x):x is number=>x!==null);
    return{intervalo,linhas,resumo:[['Funcionários ativos',staff.filter(x=>x.status==='ATIVO').length],['Técnicos ativos',staff.filter(x=>x.status==='ATIVO'&&x.cargo==='TECNICO').length],['Ordens atribuídas',linhas.reduce((s,x)=>s+x.atribuidas,0)],['Ordens concluídas',linhas.reduce((s,x)=>s+x.concluidas,0)],['Reparos realizados',linhas.reduce((s,x)=>s+x.reparos,0)],['Tempo médio',formatDuration(allDurations.length?allDurations.reduce((a,b)=>a+b,0)/allDurations.length:null)]].map(([rotulo,valor])=>({rotulo:String(rotulo),valor:String(valor)}))};
  }

  public static clientesEquipamentos(f:FiltrosRelatorio):ResultadoRelatorio<ClienteEquipamentoRelatorio> {
    const intervalo=getIntervalo(f.periodo,f.dataInicial,f.dataFinal), orders=ChamadoService.getAll().filter(x=>isInInterval(x.criadoEm,intervalo)), repairs=ManutencaoService.getAll().filter(x=>isInInterval(x.dataInicio,intervalo)), eqs=EquipamentoService.getAll(), users=UsuarioService.getAll(), minimum=Math.max(0,finite(f.quantidadeMinima)??0);
    const clients:ClienteEquipamentoRelatorio[]=users.filter(x=>(!f.clienteId||x.id===f.clienteId)&&(!f.status||x.status===f.status)).map(x=>{const equipment=eqs.filter(e=>e.clienteId===x.id), os=orders.filter(o=>o.clienteId===x.id);return{tipo:'CLIENTE' as const,id:x.id,nome:x.nome,contato:x.email,codigo:'',fabricante:'',modelo:'',cliente:x.nome,equipamentos:equipment.length,ordens:os.length,concluidas:os.filter(o=>o.status==='CONCLUIDO').length,reparos:repairs.filter(r=>equipment.some(e=>e.id===r.equipamentoId)).length,ultima:os.sort((a,b)=>b.criadoEm.localeCompare(a.criadoEm))[0]?.criadoEm??null,status:x.status};}).filter(x=>x.ordens>=minimum&&(!f.pesquisa||includes(`${x.nome} ${x.contato}`,f.pesquisa)));
    const equipmentRows:ClienteEquipamentoRelatorio[]=eqs.filter(x=>(!f.equipamentoId||x.id===f.equipamentoId)&&(!f.clienteId||x.clienteId===f.clienteId)).map(x=>{const os=orders.filter(o=>o.equipamentoId===x.id), rs=repairs.filter(r=>r.equipamentoId===x.id);return{tipo:'EQUIPAMENTO' as const,id:x.id,nome:`${x.tipo} — ${x.fabricante} ${x.modelo}`,contato:'',codigo:x.codigo,fabricante:x.fabricante,modelo:x.modelo,cliente:users.find(u=>u.id===x.clienteId)?.nome??'Cliente removido',equipamentos:1,ordens:os.length,concluidas:os.filter(o=>o.status==='CONCLUIDO').length,reparos:rs.length,ultima:[...os.map(o=>o.criadoEm),...rs.map(r=>r.dataInicio)].sort().reverse()[0]??null,status:x.status};}).filter(x=>x.ordens+x.reparos>1&&(!f.pesquisa||includes(`${x.codigo} ${x.nome} ${x.cliente}`,f.pesquisa)));
    const linhas=[...clients,...equipmentRows]; return{intervalo,linhas,resumo:[['Clientes encontrados',clients.length],['Equipamentos recorrentes',equipmentRows.length],['Ordens no período',orders.length],['Reparos no período',repairs.length]].map(([rotulo,valor])=>({rotulo:String(rotulo),valor:String(valor)}))};
  }
}
