import { AuthService } from '../../services/authService';
import { logger } from '../../services/logger';
import { downloadCsv } from '../../utils/csvExport';
import { formatIntervalo } from '../../utils/dateGrouping';
import { formatDate } from '../../utils/formatters';
import { initIcons } from '../../utils/iconHelper';
import { calculatePagination, renderPaginationControls } from '../../components/pagination';
import { Modal } from '../../components/modal';
import { Toast } from '../../components/toast';
import { ColunaRelatorio, FiltrosRelatorio, ResultadoRelatorio, TipoRelatorio } from '../../types/relatorio';
import { defaultReportFilters, renderExportMenu, renderPeriodFilters, renderPrintHeader, renderReportEmpty, renderSummary, renderTable } from '../../components/relatorios/reportComponents';
import Chart from 'chart.js/auto';

export interface ReportPageConfig<T> { tipo:TipoRelatorio; titulo:string; arquivo:string; columns:ColunaRelatorio<T>[]; extraFilters:(f:FiltrosRelatorio)=>string; readExtraFilters:(root:HTMLElement,f:FiltrosRelatorio)=>void; load:(f:FiltrosRelatorio)=>ResultadoRelatorio<T>; detail?:(row:T)=>string; filterDescription?:(f:FiltrosRelatorio)=>string; chart?:(rows:T[])=>{titulo:string;labels:string[];values:number[]}; }

export class ReportPage<T> {
  private container=document.createElement('div'); private filters=defaultReportFilters(); private result!:ResultadoRelatorio<T>; private sortKey=''; private sortDirection:'asc'|'desc'='desc'; private page=1; private readonly pageSize=15; private chart:Chart|null=null;
  public constructor(private config:ReportPageConfig<T>){this.container.className='report-page';this.config.chart??=(rows=>({titulo:'Registros filtrados',labels:['Registros'],values:[rows.length]}));}
  public render():HTMLElement { this.result=this.config.load(this.filters); this.container.innerHTML=`<div class="report-toolbar no-print"><div><span class="report-period-label">${formatIntervalo(this.result.intervalo)}</span><small>${this.result.linhas.length} ${this.result.linhas.length===1?'registro':'registros'}</small></div>${renderExportMenu(!this.result.linhas.length)}</div>${renderPeriodFilters(this.filters,this.config.extraFilters(this.filters))}<div id="report-results"></div>`; this.renderResults(); this.attachStaticEvents(); this.log('Relatório visualizado','TELA'); return this.container; }
  private sorted():T[]{const column=this.config.columns.find(c=>c.chave===this.sortKey);if(!column)return[...this.result.linhas];return[...this.result.linhas].sort((a,b)=>{const av=column.valor(a),bv=column.valor(b),comparison=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'pt-BR',{numeric:true});return this.sortDirection==='asc'?comparison:-comparison;});}
  private renderResults():void { const target=this.container.querySelector<HTMLElement>('#report-results');if(!target)return;this.chart?.destroy();this.chart=null;const sorted=this.sorted(),p=calculatePagination(sorted,this.page,this.pageSize),user=AuthService.getCurrentUser()?.nome??'Usuário',chartData=this.config.chart?.(this.result.linhas);target.innerHTML=`${renderPrintHeader(this.config.titulo,formatIntervalo(this.result.intervalo),this.config.filterDescription?.(this.filters)??'',user,this.result.linhas.length)}${renderSummary(this.result.resumo)}${chartData&&chartData.values.some(v=>v>0)?`<section class="card report-chart no-print"><h2>${chartData.titulo}</h2><div><canvas id="report-chart"></canvas></div></section>`:''}${!this.result.linhas.length?renderReportEmpty():`<section class="card report-table-card">${renderTable(this.config.columns,p.paginatedItems,this.sortKey,this.sortDirection)}<div class="no-print">${renderPaginationControls(this.page,p.totalPages,p.startItem,p.endItem,p.totalItems)}</div></section>`}`;initIcons(target);this.attachResultEvents(p.paginatedItems);if(chartData&&chartData.values.some(v=>v>0))this.initChart(chartData);}
  private attachStaticEvents():void { const period=this.container.querySelector<HTMLSelectElement>('#report-period');period?.addEventListener('change',()=>this.container.querySelector('#report-custom-dates')?.classList.toggle('visible',period.value==='PERSONALIZADO'));this.container.querySelector('#report-apply')?.addEventListener('click',()=>this.apply());this.container.querySelector('#report-clear')?.addEventListener('click',()=>this.clear());this.container.querySelector('#report-csv')?.addEventListener('click',()=>this.exportCsv());this.container.querySelector('#report-print')?.addEventListener('click',()=>{this.log('Relatório enviado para impressão','PDF');window.print();});}
  private attachResultEvents(rows:T[]):void { this.container.querySelector('#report-empty-clear')?.addEventListener('click',()=>this.clear());this.container.querySelectorAll<HTMLButtonElement>('.report-sort').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.sort??'';this.sortDirection=this.sortKey===key&&this.sortDirection==='asc'?'desc':'asc';this.sortKey=key;this.page=1;this.renderResults();}));this.container.querySelectorAll<HTMLButtonElement>('.pagination-btn[data-page]').forEach(btn=>btn.addEventListener('click',()=>{this.page=Number(btn.dataset.page)||1;this.renderResults();}));this.container.querySelectorAll<HTMLButtonElement>('.report-row-detail').forEach(btn=>btn.addEventListener('click',()=>{const row=rows[Number(btn.dataset.row)];if(row)this.openDetail(row);}));}
  private apply():void { const value=(id:string)=>this.container.querySelector<HTMLInputElement|HTMLSelectElement>(`#${id}`)?.value??'';this.filters={...this.filters,periodo:value('report-period') as FiltrosRelatorio['periodo'],dataInicial:value('report-start'),dataFinal:value('report-end'),pesquisa:value('report-search')};this.config.readExtraFilters(this.container,this.filters);this.page=1;this.result=this.config.load(this.filters);const toolbar=this.container.querySelector('.report-toolbar > div');if(toolbar)toolbar.innerHTML=`<span class="report-period-label">${formatIntervalo(this.result.intervalo)}</span><small>${this.result.linhas.length} ${this.result.linhas.length===1?'registro':'registros'}</small>`;const csv=this.container.querySelector<HTMLButtonElement>('#report-csv'),print=this.container.querySelector<HTMLButtonElement>('#report-print');if(csv)csv.disabled=!this.result.linhas.length;if(print)print.disabled=!this.result.linhas.length;this.renderResults();}
  private clear():void {this.filters=defaultReportFilters();this.page=1;this.render();}
  private exportCsv():void {if(!this.result.linhas.length)return;downloadCsv(`${this.config.arquivo}-${new Date().toISOString().slice(0,10)}.csv`,this.config.columns.map(c=>c.titulo),this.result.linhas.map(row=>this.config.columns.map(c=>c.valor(row))));this.log('Relatório exportado em CSV','CSV');Toast.success('Relatório exportado com sucesso.');}
  private openDetail(row:T):void {new Modal({title:'Detalhes do registro',content:`<div class="report-detail">${this.config.detail?this.config.detail(row):this.config.columns.map(c=>`<div><strong>${c.titulo}</strong><p>${c.html?c.html(row):String(c.valor(row)??'-')}</p></div>`).join('')}</div>`,footerButtons:[{text:'Imprimir',class:'btn-primary',onClick:()=>{this.log(this.config.tipo==='ORDENS'?'Relatório individual de ordem gerado':'Registro enviado para impressão','PDF');window.print();}},{text:'Fechar',class:'btn-secondary',onClick:m=>m.close()}]}).open();}
  private log(message:string,format:string):void {logger.info(message,{tipoRelatorio:this.config.tipo,periodo:formatIntervalo(this.result.intervalo),quantidade:this.result.linhas.length,formato:format,usuario:AuthService.getCurrentUser()?.nome??'Usuário',geradoEm:new Date().toISOString()});}
  private initChart(data:{titulo:string;labels:string[];values:number[]}):void {const canvas=this.container.querySelector<HTMLCanvasElement>('#report-chart');if(!canvas)return;const dark=document.documentElement.getAttribute('data-theme')!=='light';this.chart=new Chart(canvas,{type:'bar',data:{labels:data.labels,datasets:[{label:'Registros',data:data.values,backgroundColor:'#2563eb',borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:true}},scales:{x:{ticks:{color:dark?'#c7d7e9':'#334155'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:dark?'#c7d7e9':'#334155',precision:0},grid:{color:dark?'rgba(255,255,255,.08)':'rgba(15,23,42,.08)'}}}}});}
}

export const dateValue=(value:string|null):string=>formatDate(value);
export function groupChart<T>(titulo:string,rows:T[],label:(row:T)=>string,value:((row:T)=>number)=()=>1):{titulo:string;labels:string[];values:number[]}{const grouped=new Map<string,number>();rows.forEach(row=>grouped.set(label(row),(grouped.get(label(row))??0)+value(row)));return{titulo,labels:[...grouped.keys()],values:[...grouped.values()]};}
